name: her_safe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  url_launcher: ^6.0.20
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/siren.mp3
