name: she_safe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  url_launcher: ^6.0.20
  permission_handler: ^11.0.0
  flutter_map: ^6.0.1
  latlong2: ^0.9.0

  # ✅ Firebase dependencies
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/siren.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
